openapi: 3.0.0
info:
  title: Wall
  version: '1.0'
servers:
  - url: 'https://api.wall.one'
    description: Production
paths:
  /auth/login:
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-auth-login
    post:
      summary: Login
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth+Response'
              examples: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      description: Login user and get token.
      tags:
        - auth
  /articles:
    get:
      summary: Get all articles
      tags:
        - article
        - get
        - all
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response+Article'
              examples:
                example-1:
                  value:
                    data:
                      - id: string
                        title: string
                        content: string
                        image: string
                        articleCategory:
                          id: string
                          title: string
      operationId: get-articles
      description: Get all articles
components:
  schemas:
    Model+Response+Article:
      title: Model+Response+Article
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        image:
          type: string
        articleCategory:
          $ref: '#/components/schemas/Model+Response+ArticleCategory'
    Model+Response+ArticleCategory:
      title: Model+Response+ArticleCategory
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    Response+Article:
      title: Response+Article
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Model+Response+Article'
    Auth+Request:
      title: Auth+Request
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
      x-examples:
        example-1:
          email: test@test.com
          password: testtest
    Auth+Response:
      description: Response for auth requests.
      type: object
      properties:
        accessToken:
          type: string
          minLength: 1
        tokenType:
          type: string
          minLength: 1
        expiresIn:
          type: number
      required:
        - accessToken
        - tokenType
        - expiresIn
      title: Auth+Response
  securitySchemes:
    Token:
      name: Authorization
      type: apiKey
      in: header
tags:
  - name: auth
  - name: article
  - name: get
  - name: all
